### ISSUE TITLE
 Error don't install failed in  composer require hyn/multi-tenant. Help

### ISSUE THREAD

**Issue by thandonguocmo2020** [hyn/dummy-tenant-website#1]
- hyn/framework 0.1.2 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
  - don't install illuminate/support v5.0.0|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.22|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.25|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.26|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.28|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.33|don't install laravel/framework v5.3.9
  - don't install illuminate/support v5.0.4|don't install laravel/framework v5.3.9
  - Installation request for laravel/framework (locked at v5.3.9, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.9].
  - Installation request for hyn/multi-tenant ^1.0 -> satisfiable by hyn/multi-tenant[1.0.0, 1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by Diddyy** [comment]
Old but, this is fixed by making sure that your PHP is up to date with the requirements which now is PHP 7+. Anyone experiencing the issue above should make sure they are running PHP 7.

**Comment by Luceos** [comment]
@Diddyy thanks for answering, must have missed this issue completely!
